name: Run JMeter Test

on:
  workflow_dispatch:

jobs:

  performance-test:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Install Java
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17

    - name: Install JMeter
      run: |
        wget https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.6.3.tgz
        tar -xzf apache-jmeter-5.6.3.tgz

    - name: Run Test
      run: |
        apache-jmeter-5.6.3/bin/jmeter \
        -n \
        -t jmeter/LoginTest.jmx \
        -l results.jtl \
        -e \
        -o reports

    - name: Upload Report
      uses: actions/upload-artifact@v4
      with:
        name: JMeter-Report
        path: reports/
